config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get 'welcome/disclaimer'
  
  resources :candidates, only: [:new, :create]
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :specializations
  has_many :specialties, through: :specializations
  has_many :categories, through: :specialties
  
  accepts_nested_attributes_for :specializations
  accepts_nested_attributes_for :specialties
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :specialties
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :specialty

  accepts_nested_attributes_for :specialty
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  belongs_to :category

  accepts_nested_attributes_for :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:first_name,
                                      :last_name,
                                      :email,
                                      :phone,
                                      :category,
                                      :date_available,
                                      :education,
                                      :languages,
                                      :background_check,
                                      :drug_screen,
                                      :work_type,
                                      :shifts,
                                      :category,
                                      :eligible,
                                      :specialty_ids,
                                      :zipcode,
                                      :radius
                                      )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end
end

app/helpers/VideoHelper.rb
module VideoHelper

  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def education_types_for_select
    ["No/Some High School", "GED", "HS Diploma", "Associate Degree", "College Degree"]
  end

  def languages_for_select
    ["English", "Spanish", "Portugese", "Mandarin", "Vietnamese"]
  end

  def work_types_for_select
    ["Temporary", "Full Time", "Both"]
  end

  def shifts_for_select
    ["Any", "Days Only", "Afternoons Only", "Midnights Only", "Days and Afternoons", "Afternoons and Nights", "Days and Nights"]
  end

  def admin_specialties
    Specialty.where(category_id: 1).map { |specialty| [specialty.name]}
  end

  def contact_specialties
    Specialty.where(category_id: 2).map { |specialty| [specialty.name]}
  end

  def industry_specialties
    Specialty.where(category_id: 3).map { |specialty| [specialty.name]}
  end

  def trade_specialties
    Specialty.where(category_id: 4).map { |specialty| [specialty.name]}
  end

  def specialties_for_select
    specialties = []
    admin = ['Administrative']
    admin << admin_specialties
    specialties << admin
    contacts = ['Contact Center']
    contacts << contact_specialties
    specialties << contacts
    industry = ["Industrial"]
    industry << industry_specialties
    specialties << industry
    skill = ["Skilled Trades"]
    skill << trade_specialties
    specialties << skill
    specialties
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_topbar.html.erb
<nav class="topbar">
  <%= link_to root_path do %>
    <%= image_tag('logo_manpower.png') %>
  <% end %>
  <hr>
</nav>

app/views/application/_typekit.html.erb
<script src="//use.typekit.net/yye6ylr.js"></script>
<script>try{Typekit.load();}catch(e){}</script>

app/views/candidates/_form_errors.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <p><%= pluralize(object.errors.count, 'error') %> prohibited this user from being submitted:</p>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/candidates/new.html.erb
<%= render "topbar" %>
<%= render 'form_errors.html.erb', object: @candidate  %>
<div class= candidate-div>
<h2>See what's humanly possible.</h2>
<h3>Register with us today.</h3>
<%= simple_form_for @candidate, url: candidates_path do |form| %>
  <%= form.input :first_name, label: 'Name', placeholder: 'First Name', error: false %>
  <%= form.input :last_name, label: false, placeholder: 'Last Name', error: false %>
  <%= form.input :email, placeholder: 'myemail@mail.com', error: false %>
  <%= form.input :phone, placeholder: '555-5555', error: false %>
  <%= form.input :zipcode, placeholder: '53202', error: false %>
  <%= form.input :radius, placeholder: '20', label: 'Miles Willing to Travel', error: false %>
  <%= form.input :date_available, as: :date, html5: true %>
  <%= form.input :education do %>
    <%= form.select :education, education_types_for_select %>
  <% end %>
  <%= form.input :languages, label: 'Main spoken language' do %>
    <%= form.select :languages, languages_for_select%>
  <% end %>
  <%= form.input :work_type, label: 'Preferred Type of Work' do %>
    <%= form.select :work_type, work_types_for_select %>
  <% end %>
  <%= form.input :shifts, label: 'Preferred Shift' do %>
    <%= form.select :shifts, shifts_for_select %>
  <% end %>
  <%= form.association :specialties, as: :grouped_select, collection: specialties_for_select, group_method: :last, label: "Select All Positions of Interest" %>
  <%= form.input :eligible, as: :boolean, value: '1', label: 'I am 18 years old or older and eligible to work in the United States.'%>
  <div class="modal">
    <label for="modal-1">
      <div class="modal-trigger">Register</div>
    </label>
    <input class="modal-state" id="modal-1" type="checkbox" />
    <div class="modal-fade-screen">
      <div class="modal-inner">
        <label class="modal-close" for="modal-1"></label>
        <%= image_tag('logo_manpower_small.png') %>
        <p class="modal-intro">I certify that all of the information presented here is accurate and complete.</p>
        <%= form.button :submit, 'Register' %> <%= link_to 'Cancel', root_path %></p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "jquery.multiselect." + I18n.locale.to_s %>
  <%= javascript_include_tag "jquery.multiselect.filter." + I18n.locale.to_s %>
  <link href="./ply.css" rel="stylesheet" type="text/css"/>
</head>
<body class="<%= body_class %>">
  <div class="content">
    <main>
      <%= render 'flashes' -%>
      <%= yield %>
    </main>
  </div>
  <%= render 'javascript' -%>
</body>
</html>

app/views/welcome/disclaimer.html.erb
<%= render "topbar" %>
<div class="disclaimer">
  <h1>Are you 18 or older and eligible to work in the United States?</h1>
  <br>
</div>
<div class="modal">
  <label for="modal-1">
    <div class="modal-trigger"><%= link_to 'Yes | ', new_candidate_path %>No</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <label class="modal-close" for="modal-1"></label>
      <%= image_tag('logo_manpower_small.png') %>
      <p class="modal-intro">Unfortunately, at this time we are unable to place anyone who is under 18 or not legally eligible to work in the United States.</p>
      <p class="modal-intro">Thank you for your interest and please come back when you're eligible.</p>
      <%= link_to 'Close', root_path %>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<%= render "topbar" %>
<div class='home'>
  <span><h1>Welcome |</h1><h2>The Age of Options Has Begun</h1></span>
  <%= image_tag('image1.png') %>
    <h3>Please <%= link_to 'register', welcome_disclaimer_path %> with us to get started.</h3>
</div>